In [2]:
import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import joblib

# Load dataset
file_path = 'C:/Users/admin/Documents/Income_Prediction_ADS/dataset1.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(df.head())

# Display general information about the dataset
print(df.info())

# Display summary statistics
print(df.describe())

# Check for missing values
print(df.isnull().sum())

# Use the pd.get_dummies() function for one-hot encoding
df_encoded = pd.get_dummies(df, columns=['marital', 'ed', 'jobsat', 'gender'], drop_first=True)

# Display the first few rows of the DataFrame after encoding
print(df_encoded.head())

# Select relevant features
features = ['employ', 'car', 'carcat', 'age', 'inccat']

# Split the data into features (X) and target variable (y)
X = df[features]
y = df['income']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
linear_regression_model = LinearRegression()

# Fit the model to the training data
linear_regression_model.fit(X_train, y_train)

# Display the coefficients and intercept
print("Coefficients:", linear_regression_model.coef_)
print("Intercept:", linear_regression_model.intercept_)

# Make predictions on the test set
y_pred = linear_regression_model.predict(X_test)

# Evaluation metrics
from sklearn.metrics import mean_squared_error, r2_score

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

# Create a summary of the OLS regression results
X_train_with_intercept = sm.add_constant(X_train)
ols_model = sm.OLS(y_train, X_train_with_intercept).fit()
print(ols_model.summary())

# Save the best model using joblib
best_model = linear_regression_model
joblib.dump(best_model, "C:/Users/admin/Documents/Income_Prediction_ADS/best_model3.pkl")

   age  marital  address  income  inccat   car  carcat  ed  employ  retire  \
0   55        1       12      72       3  36.2       3   1      23       0
1   56        0       29     153       4  76.9       3   1      35       0
2   28        1        9      28       2  13.7       1   3       4       0
3   24        1        4      26       2  12.5       1   4       0       0
4   25        0        2      23       1  11.3       1   2       5       0

   ...  callid  callwait owntv  ownvcr  owncd  ownpda  ownpc  ownfax  news  \
0  ...       0         0     1       1      1       0      0       0     0
1  ...       1         1     1       1      1       0      0       0     0
2  ...       1         1     1       1      1       1      1       0     1
3  ...       0         1     1       1      1       1      1       1     1
4  ...       1         0     1       1      1       0      0       0     1

   response
0         1
1         0
2         1
3         1
4         1

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6400 entries, 0 to 6399
Data columns (total 29 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       6400 non-null   int64
 1   marital   6400 non-null   int64
 2   address   6400 non-null   int64
 3   income    6400 non-null   int64
 4   inccat    6400 non-null   int64
 5   car       6400 non-null   float64
 6   carcat    6400 non-null   int64
 7   ed        6400 non-null   int64
 8   employ    6400 non-null   int64
 9   retire    6400 non-null   int64
 10  empcat    6400 non-null   int64
 11  jobsat    6400 non-null   int64
 12  gender    6400 non-null   object
 13  reside    6400 non-null   int64
 14  wireless  6400 non-null   int64
 15  multline  6400 non-null   int64
 16  voice     6400 non-null   int64
 17  pager     6400 non-null   int64
 18  internet  6400 non-null   int64
 19  callid    6400 non-null   int64
 20  callwait  6400 non-null   int64
 21  owntv     6400 non-null   int64
 22  ownvcr    6400 non-null   int64
 23  owncd     6400 non-null   int64
 24  ownpda    6400 non-null   int64
 25  ownpc     6400 non-null   int64
 26  ownfax    6400 non-null   int64
 27  news      6400 non-null   int64
 28  response  6400 non-null   int64
dtypes: float64(1), int64(27), object(1)
memory usage: 1.4+ MB
None
               age      marital      address       income       inccat  \
count  6400.000000  6400.000000  6400.000000  6400.000000  6400.000000
mean     42.058594     0.496250    11.559844    69.474844     2.528437
std      12.289516     0.500025     9.938136    78.718564     1.073835
min      18.000000     0.000000     0.000000     9.000000     1.000000
25%      33.000000     0.000000     3.000000    28.000000     2.000000
50%      41.000000     0.000000     9.000000    45.000000     2.000000
75%      51.000000     1.000000    17.000000    79.000000     4.000000
max      77.000000     1.000000    56.000000  1116.000000     4.000000

               car       carcat           ed       employ       retire  ...  \
count  6400.000000  6400.000000  6400.000000  6400.000000  6400.000000  ...
mean     30.128375     2.069219     2.587031    10.566250     0.048125  ...
std      21.926917     0.799900     1.198760     9.724458     0.214047  ...
min       4.200000     1.000000     1.000000     0.000000     0.000000  ...
25%      13.900000     1.000000     2.000000     3.000000     0.000000  ...
50%      22.200000     2.000000     2.000000     8.000000     0.000000  ...
75%      39.500000     3.000000     4.000000    16.000000     0.000000  ...
max      99.900000     3.000000     5.000000    57.000000     1.000000  ...

            callid     callwait        owntv       ownvcr        owncd  \
count  6400.000000  6400.000000  6400.000000  6400.000000  6400.000000
mean      0.510469     0.507344     0.990156     0.960156     0.969688
std       0.499929     0.499985     0.098734     0.195607     0.171459
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     1.000000     1.000000     1.000000
50%       1.000000     1.000000     1.000000     1.000000     1.000000
75%       1.000000     1.000000     1.000000     1.000000     1.000000
max       1.000000     1.000000     1.000000     1.000000     1.000000

            ownpda        ownpc       ownfax         news     response
count  6400.000000  6400.000000  6400.000000  6400.000000  6400.000000
mean      0.204219     0.439219     0.187812     0.567500     0.893906
std       0.403161     0.496331     0.390593     0.495462     0.307982
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     1.000000
50%       0.000000     0.000000     0.000000     1.000000     1.000000
75%       0.000000     1.000000     0.000000     1.000000     1.000000
max       1.000000     1.000000     1.000000     1.000000     1.000000

[8 rows x 28 columns]
age         0
marital     0
address     0
income      0
inccat      0
car         0
carcat      0
ed          0
employ      0
retire      0
empcat      0
jobsat      0
gender      0
reside      0
wireless    0
multline    0
voice       0
pager       0
internet    0
callid      0
callwait    0
owntv       0
ownvcr      0
owncd       0
ownpda      0
ownpc       0
ownfax      0
news        0
response    0
dtype: int64
   age  address  income  inccat   car  carcat  employ  retire  empcat  reside  \
0   55       12      72       3  36.2       3      23       0       3       4
1   56       29     153       4  76.9       3      35       0       3       1
2   28        9      28       2  13.7       1       4       0       1       3
3   24        4      26       2  12.5       1       0       0       1       3
4   25        2      23       1  11.3       1       5       0       2       2

   ...  marital_1   ed_2   ed_3   ed_4   ed_5  jobsat_2  jobsat_3  jobsat_4  \
0  ...       True  False  False  False  False     False     False     False
1  ...      False  False  False  False  False     False     False      True
2  ...       True  False   True  False  False     False      True     False
3  ...       True  False  False   True  False     False     False     False
4  ...      False   True  False  False  False      True     False     False

   jobsat_5  gender_m
0      True     False
1     False      True
2     False     False
3     False      True
4     False      True

[5 rows x 35 columns]
Coefficients: [ 1.08129104  3.20056185 -9.54226186 -0.04717766 -9.0761241 ]
Intercept: 6.27153488009283
Mean Squared Error: 2541.042845222758
R-squared: 0.6102971343559671
                            OLS Regression Results
==============================================================================
Dep. Variable:                 income   R-squared:                       0.659
Model:                            OLS   Adj. R-squared:                  0.659
Method:                 Least Squares   F-statistic:                     1977.
Date:                Tue, 05 Dec 2023   Prob (F-statistic):               0.00
Time:                        17:12:12   Log-Likelihood:                -26830.
No. Observations:                5120   AIC:                         5.367e+04
Df Residuals:                    5114   BIC:                         5.371e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.2715      2.976      2.107      0.035       0.436      12.107
employ         1.0813      0.101     10.677      0.000       0.883       1.280
car            3.2006      0.065     49.255      0.000       3.073       3.328
carcat        -9.5423      1.836     -5.198      0.000     -13.141      -5.943
age           -0.0472      0.066     -0.714      0.475      -0.177       0.082
inccat        -9.0761      1.662     -5.461      0.000     -12.334      -5.818
==============================================================================
Omnibus:                     7484.096   Durbin-Watson:                   1.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          3462252.587
Skew:                           8.714   Prob(JB):                         0.00
Kurtosis:                     129.197   Cond. No.                         270.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

['C:/Users/admin/Documents/Income_Prediction_ADS/best_model3.pkl']